include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_relative_imports
    - sized_box_for_whitespace
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - avoid_redundant_argument_values
    - prefer_single_quotes
    - require_trailing_commas
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  errors:
    invalid_annotation_target: ignore
    # .env is optional; we fall back to .env.example so the missing asset info is benign
    asset_does_not_exist: ignore
